---
- hosts: ops_server
  become: true
  tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
    - name: Run wireguard container
      community.docker.docker_container:
        name: wireguard
        image: linuxserver/wireguard
        ports:
          - "51820:51820/udp"
        env:
          SERVERURL: "{{ ansible_host }}"
          SERVERPORT: "51820"
          PEERS: "1"
          PEERDNS: "auto"
          INTERNAL_SUBNET: "10.13.13.0"
          ALLOWEDIPS: "0.0.0.0/0"
          LOG_CONFS: "true"
        volumes:
          - config:/config
          - /lib/modules:/lib/modules
        capabilities:
          - NET_ADMIN
          - SYS_MODULE  
        sysctls:
          net.ipv4.conf.all.src_valid_mark: 1
        restart_policy: unless-stopped
    - name: get configurations
      shell: 'docker exec -it wireguard cat /config/peer1/peer1.conf'
      register: peer_config

    - debug:
        var: peer_config.stdout_lines