---
- hosts: ops_server
  become_user: ubuntu
  tasks: 

    - name: build container image
      local_action:
        module: docker_image
        name: my_jenkins:v1.0
        build:
          path: ../jenkins
        source: build

    - name: archive container image as a tarball
      local_action:
        module: docker_image
        name: my_jenkins:v1.0
        archive_path: ./my_jenkins:v1.0.tar
        source: pull

    - name: copy tarball to server
      copy:
        src: ./my_jenkins:v1.0.tar
        dest: /home/ubuntu/my_jenkins:v1.0.tar

    - name: load container from tarball
      docker_image:
        name: my_jenkins:v1.0
        load_path: /home/ubuntu/my_jenkins:v1.0.tar
        source: load

    - name: Run jenkins container
      community.docker.docker_container:
        name: jenkins
        image: my_jenkins:v1.0
        ports:
          - "8080:8080"
        volumes:
#          - /home/ubuntu/jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock  
        env:
          JENKINS_ADMIN_ID: "{{ username }}"
          JENKINS_ADMIN_PASSWORD: "{{ password }}"
    
    - name: Remove image from local
      local_action:
        module: docker_image
        state: absent
        name: my_jenkins
        tag: v1.0

    - name: rm local tar file
      local_action:
        module: file
        path: ./my_jenkins:v1.0.tar
        state: absent
    
    - name: rm tar file in server
      file:
        path: /home/ubuntu/my_jenkins:v1.0.tar
        state: absent
