---
- hosts: ops_server
  tasks: 


    - name: Copy certs and conf file to server
      copy:
        src: ../nginx/
        dest: /home/ubuntu/
    - name: Run Nexus container
      community.docker.docker_container:
        name: nginx
        image: nginx
        networks:
          - name: "ops_network"
        ports:
          - "443:443"
        volumes:
           - /home/ubuntu/fullchain.pem:/etc/nginx/ssl/fullchain.pem
           - /home/ubuntu/privkey.pem:/etc/nginx/ssl/privkey.pem
           - /home/ubuntu/nexus.conf:/etc/nginx/conf.d/default.conf
        restart_policy: unless-stopped