---
- hosts: ops_server
  become: yes
  tasks:
  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: install prerequisites
    apt:
      name:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent
      - software-properties-common
      - python3
      - python3-pip
  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
  - name: install docker 
    apt:
      name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      update_cache: yes
  - name: add userpermissions
    shell: "usermod -aG docker ubuntu"
  - name: Install docker python package
    become_user: ubuntu
    pip:
        name: 
         - docker
         - docker-compose

  - name: Create a network
    docker_network:
      name: ops_network