---
- hosts: ops_server
  become: yes
  tasks:
  - name: install prerequisites
    apt:
      name:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent
      - software-properties-common
      - python3
      - python3-pip
      update_cache: yes
  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
  - name: install docker 
    apt:
      name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      update_cache: yes
  - name: add userpermissions
    shell: "usermod -aG docker ubuntu"
  - name: Install docker python package
    become_user: ubuntu
    pip:
        name: 
         - docker
         - docker-compose