---

- hosts: ops_server
  become_user: ubuntu
  tasks: 

    - name: build container image
      local_action:
        module: docker_image
        name: my_jenkins:v1.0
        build:
          path: ../jenkins
        source: build

    - name: archive container image as a tarball
      local_action:
        module: docker_image
        name: my_jenkins:v1.0
        archive_path: ./my_jenkins:v1.0.tar
        source: pull

    - name: copy tarball to server
      copy:
        src: ./my_jenkins:v1.0.tar
        dest: /home/ubuntu/my_jenkins:v1.0.tar

    - name: load container from tarball
      docker_image:
        name: my_jenkins:v1.0
        load_path: /home/ubuntu/my_jenkins:v1.0.tar
        source: load

    - name: Run jenkins container
      docker_container:
        name: jenkins
        image: my_jenkins:v1.0
        networks:
          - name: "ops_network"
        ports:
          - "8080:8080"
        volumes:
          - jenkins_workspace:/var/jenkins_home/workspace
          - /var/run/docker.sock:/var/run/docker.sock  
        env:
          JENKINS_ADMIN_ID: "{{ username }}"
          JENKINS_ADMIN_PASSWORD: "{{ password }}"
          NEXUS_PASSWORD: "{{ nexus_password }}"
          AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
          AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        restart_policy: unless-stopped
    
    - name: Remove image from local
      local_action:
        module: docker_image
        state: absent
        name: my_jenkins
        tag: v1.0

    - name: rm local tar file
      local_action:
        module: file
        path: ./my_jenkins:v1.0.tar
        state: absent
    
    - name: rm tar file in server
      file:
        path: /home/ubuntu/my_jenkins:v1.0.tar
        state: absent

    - name: configuring kubernernetes deployement file with out data  
      local_action: shell cat ../kube/django_web_ex.yml | \
        sed -e "s#%%SQL_HOST%%#{{sql_host}}#" > ../kube/django_web.yml


    - name: copy kube deployment to server
      copy:
        src: ../kube/django_web.yml
        dest: /home/ubuntu/django_web.yml

    - name: rm that temporary file
      local_action:
        module: file
        path: ../kube/django_web.yml
        state: absent
